export const COOKIES = {
  breadcrumbs: [
    { label: 'Головна', href: '/' },
    { label: 'Повідомлення про Cookies' },
  ],
  title: 'Повідомлення про Cookies',
  intro: 'Під час першого відвідування нашого веб-сайту вам буде запропоновано прийняти розміщення файлів cookie на вашому пристрої. Подальше використання веб-сайту означає вашу згоду з цим. Ви можете відхилити файли cookie, дотримуючись наведених нижче інструкцій.',
  blocks: [
    { type: 'h2', text: 'ПРО ФАЙЛИ COOKIE' },
    { type: 'p', content: ['Файл cookie — це невеликий текстовий файл, який зберігається на вашому комп’ютері. Файли cookie дозволяють нам:'] },
    { type: 'list', items: [
      ['розпізнавати ваш комп’ютер або пристрій під час відвідування нашого веб-сайту з метою надання вам більш особистого досвіду;'],
      ['спостерігати за використанням вами нашого веб-сайту, включаючи отримання інформації про кількість відвідувачів та їх поведінку. Чим краще ми розуміємо, як використовується наш веб-сайт, тим краще ми зможемо його адаптувати.'],
    ] },
    { type: 'p', content: ['Щоб отримати більш загальну інформацію про файли cookie, перегляньте', { t: 'статтю Вікіпедії про файли HTTP-cookie', href: 'https://en.wikipedia.org/wiki/HTTP_cookie' }, '.'] },
    { type: 'h2', text: 'НАШІ ТИПИ COOKIES' },
    { type: 'p', content: ['Ми використовуємо такі типи файлів cookie:'] },
    {
      type: 'table',
      headers: ['Назва файлу cookie', 'Домен. Постачальник і посилання на його правила', 'Опис', 'Час зберігання', 'Тип'],
      rows: [
        [['pageHistory'], ['.yalantis.com постачальник – 1 сторона'], ['Cookies історії сторінок використовуються Yalantis для відстеження послідовності сторінок, які відвідав користувач'], ['session'], ['Вимірювання аудиторії']],
        [['cookieyes-consent'], ['.yalantis.com', { t: 'CookieYes', href: 'https://www.cookieyes.com/privacy-policy/' }], ['CookieYes встановлює цей файл cookie для запам’ятовування налаштувань згоди користувачів, щоб їхні уподобання враховувалися під час наступних відвідувань цього сайту. Він не збирає та не зберігає жодної особистої інформації про відвідувачів сайту.'], ['1 рік'], ['Суттєві']],
        [['CLID'], ['.clarity.ms', { t: 'Microsoft Clarity', href: 'https://privacy.microsoft.com/en-gb/privacystatement' }], ['Microsoft Clarity встановлює цей файл cookie для зберігання інформації про вас, як відвідувачі взаємодіють із веб-сайтом. Файл cookie додатково надати звіт про аналіз. Збір даних включає кількість відвідувачів, місця відвідування веб-сайту та відвідані сторінки.'], ['1 рік'], ['Вимірювання аудиторії']],
        [['_gcl_au'], ['.yalantis.com', { t: 'Google Privacy Policy', href: 'https://policies.google.com/privacy?hl=en' }, { t: 'Google Marketing Platform', href: 'https://business.safety.google/adscookies/' }], ['Менеджер тегів Google встановлює файли cookie, щоб експериментувати з ефективністю реклами веб-сайтів, які використовують їхні служби.'], ['3 місяців'], ['Маркетинг']],
        [['test_cookie'], ['.doubleclick.net', { t: 'Google Privacy Policy', href: 'https://policies.google.com/privacy?hl=en' }, { t: 'Google Marketing Platform', href: 'https://business.safety.google/adscookies/' }], ['doubleclick.net встановлює цей файл cookie, щоб визначити, чи підтримує браузер користувача файли cookie.'], ['15 хвилин'], ['Маркетинг']],
        [['_clck'], ['.yalantis.com', { t: 'Microsoft Clarity', href: 'https://privacy.microsoft.com/en-gb/privacystatement' }], ['Microsoft Clarity встановлює цей файл cookie для збереження ідентифікатора користувача Clarity браузера та налаштувань, ексклюзивних для цього веб-сайту. Це гарантує, що дії, здійснені під час наступних відвідувань того самого веб-сайту, будуть пов’язані з тим самим ідентифікатором користувача.'], ['1 рік'], ['Маркетинг']],
        [['li_sugr'], ['.linkedin.com', { t: 'LinkedIn', href: 'https://www.linkedin.com/legal/privacy-policy' }], ['LinkedIn встановлює цей файл cookie для збору даних про поведінку користувачів, щоб оптимізувати веб-сайт і зробити рекламу на веб-сайті більш актуальною.'], ['3 місяці'], ['Маркетинг']],
        [['bcookie'], ['.linkedin.com', { t: 'LinkedIn', href: 'https://www.linkedin.com/legal/privacy-policy' }], ['LinkedIn встановлює цей файл cookie з кнопок спільного доступу LinkedIn і тегів оголошень для розпізнавання ідентифікаторів браузера.'], ['1 рік'], ['Маркетинг']],
        [['lidc'], ['.linkedin.com', { t: 'LinkedIn', href: 'https://www.linkedin.com/legal/privacy-policy' }], ['LinkedIn встановлює файл cookie lidc, щоб полегшити вибір центру обробки даних.'], ['1 рік'], ['Вимірювання аудиторії']],
        [['_ga'], ['.yalantis.com', { t: 'Google Privacy Policy', href: 'https://policies.google.com/privacy?hl=en' }, { t: 'Google Marketing Platform', href: 'https://business.safety.google/adscookies/' }], ['Google Analytics встановлює цей файл cookie для обчислення даних відвідувачів, сеансів і кампаній і відстеження використання сайту для аналітичного звіту сайту. Файл cookie зберігає інформацію анонімно та призначає випадково згенерований номер для розпізнавання унікальних відвідувачів.'], ['1 рік 1 місяць 4 днів'], ['Вимірювання аудиторії']],
        [['_gid'], ['.yalantis.com', { t: 'Google Privacy Policy', href: 'https://policies.google.com/privacy?hl=en' }, { t: 'Google Marketing Platform', href: 'https://business.safety.google/adscookies/' }], ['Google Analytics встановлює цей файл cookie для зберігання інформації про те, як відвідувачі використовують веб-сайт, а також створює аналітичний звіт про ефективність веб-сайту.'], ['1 рік'], ['Вимірювання аудиторії']],
        [['_gat_UA-*'], ['.yalantis.com', { t: 'Google Privacy Policy', href: 'https://policies.google.com/privacy?hl=en' }, { t: 'Google Marketing Platform', href: 'https://business.safety.google/adscookies/' }], ['Google Analytics встановлює цей файл cookie для відстеження поведінки користувачів.'], ['1 хвилина'], ['Вимірювання аудиторії']],
        [['UserMatchHistory'], ['.linkedin.com', { t: 'LinkedIn', href: 'https://www.linkedin.com/legal/privacy-policy' }], ['LinkedIn встановлює цей файл cookie для синхронізації ідентифікатора оголошень LinkedIn.'], ['1 місяць'], ['Маркетинг']],
        [['AnalyticsSyncHistory'], ['.linkedin.com', { t: 'LinkedIn', href: 'https://www.linkedin.com/legal/privacy-policy' }], ['Linkedin налаштував цей файл cookie для зберігання інформації про час синхронізації з файлом cookie lms_analytics.'], ['1 місяць'], ['Маркетинг']],
        [['_ga_*'], ['.yalantis.com', { t: 'Google Privacy Policy', href: 'https://policies.google.com/privacy?hl=en' }, { t: 'Google Marketing Platform', href: 'https://business.safety.google/adscookies/' }], ['Google Analytics встановлює цей файл cookie для зберігання та підрахунку переглядів сторінок.'], ['1 рік 1 місяць 4 днів'], ['Вимірювання аудиторії']],
        [['ln_or'], ['.yalantis.com', { t: 'LinkedIn', href: 'https://www.linkedin.com/legal/privacy-policy' }], ['Linkedin встановлює цей файл cookie для реєстрації статистичних даних про поведінку користувачів на веб-сайті для внутрішньої аналітики.'], ['1 день'], ['Вимірювання аудиторії']],
        [['bscookie'], ['.linkedin.com', { t: 'LinkedIn', href: 'https://www.linkedin.com/legal/privacy-policy' }], ['LinkedIn встановлює цей файл cookie для зберігання виконаних дій на веб-сайті.'], ['1 рік'], ['Маркетинг']],
        [['li_gc'], ['.linkedin.com', { t: 'LinkedIn', href: 'https://www.linkedin.com/legal/privacy-policy' }], ['LinkedIn встановлює цей файл cookie для зберігання виконаних дій на веб-сайті.'], ['5 місяців 27 днів'], ['Маркетинг']],
        [['_clsk'], ['.yalantis.com', { t: 'Microsoft Clarity', href: 'https://privacy.microsoft.com/en-gb/privacystatement' }], ['Microsoft Clarity встановлює цей файл cookie для зберігання та об’єднання переглядів сторінок користувача в один запис сеансу.'], ['1 день'], ['Вимірювання аудиторії']],
        [['_fbp'], ['.yalantis.com', { t: 'Facebook', href: 'https://www.facebook.com/privacy/policy/' }, '(Meta)'], ['Facebook встановлює цей файл cookie для відображення реклами на Facebook або на цифровій платформі, що підтримує рекламу Facebook, після відвідування веб-сайту.'], ['3 місяці'], ['Маркетинг']],
        [['SM'], ['.c.clarity.ms', { t: 'Microsoft Clarity', href: 'https://privacy.microsoft.com/en-gb/privacystatement' }], ['Файл cookie Microsoft Clarity встановлює цей файл cookie для синхронізації MUID між доменами Microsoft.'], ['сесія'], ['Маркетинг']],
        [['MUID'], ['.clarity.ms', { t: 'Microsoft Clarity', href: 'https://privacy.microsoft.com/en-gb/privacystatement' }], ['Bing встановлює цей файл cookie для розпізнавання унікальних веб-переглядачів, які відвідують сайти Microsoft. Цей файл cookie використовується для реклами, аналітики сайту та інших операцій.'], ['1 рік 24 дня'], ['Маркетинг']],
        [['MUID'], ['.bing.com', { t: 'Microsoft Clarity', href: 'https://privacy.microsoft.com/en-gb/privacystatement' }], ['Bing встановлює цей файл cookie для розпізнавання унікальних веб-переглядачів, які відвідують сайти Microsoft. Цей файл cookie використовується для реклами, аналітики сайту та інших операцій.'], ['1 рік 24 дня'], ['Маркетинг']],
        [['MR'], ['.c.bing.com', { t: 'Microsoft Clarity', href: 'https://privacy.microsoft.com/en-gb/privacystatement' }], ['Цей файл cookie, встановлений компанією Bing, використовується для збору інформації про користувача з метою аналітики.'], ['7 днів'], ['Вимірювання аудиторії']],
        [['SRM_B'], ['.c.bing.com', { t: 'Microsoft Clarity', href: 'https://privacy.microsoft.com/en-gb/privacystatement' }], ['Використовується Microsoft Advertising як унікальний ідентифікатор для відвідувачів.'], ['1 рік 24 дня'], ['Маркетинг']],
        [['MR'], ['.c.clarity.ms', { t: 'Microsoft Clarity', href: 'https://privacy.microsoft.com/en-gb/privacystatement' }], ['Цей файл cookie, встановлений компанією Bing, використовується для збору інформації про користувача з метою аналітики.'], ['7 днів'], ['Вимірювання аудиторії']],
        [['ANONCHK'], ['.c.clarity.ms', { t: 'Microsoft Clarity', href: 'https://privacy.microsoft.com/en-gb/privacystatement' }], ['Файл cookie ANONCHK, встановлений Bing, використовується для зберігання ідентифікатора сеансу користувача та перевірки кліків оголошень у пошуковій системі Bing. Файли cookie також допомагають у звітності та персоналізації.'], ['10 хвилин'], ['Маркетинг']],
      ],
    },
    { type: 'h2', text: 'ВІДХИЛИТИ АБО ВИДАЛИТИ ФАЙЛИ COOKIE' },
    { type: 'p', content: ['Ви можете вимкнути файли cookie у своєму браузері, зокрема видалити історію веб-переглядача.'] },
    { type: 'p', content: ['> Подивіться, як на', { t: 'aboutcookies.org', href: 'https://www.aboutcookies.org/' }] },
    { type: 'p', content: ['Якщо ви вирішите заблокувати або видалити наші файли cookie, ви не зможете отримати доступ до певних функцій веб-сайту, що може вплинути на роботу веб-сайту.'] },
    { type: 'p', content: ['Ви завжди можете відхилити файли cookie, змінивши налаштування конфіденційності свого браузера.'] },
    { type: 'h2', text: 'ОБРОБКА ВАШИХ ПЕРСОНАЛЬНИХ ДАНИХ' },
    { type: 'p', content: ['Якщо ви хочете дізнатися більше про те, як Yalantis обробляє персональні дані у зв’язку з вашим використанням нашого веб-сайту, ви можете знайти наше', { t: 'Повідомлення про приватність', href: '/privacy-policy' }, 'тут.'] },
    { type: 'h2', text: 'КОНТАКТНА ІНФОРМАЦІЯ' },
    { type: 'p', content: ['Якщо у вас виникнуть запитання щодо нашого Повідомлення про файли cookie, зв’яжіться з нами за адресою', { t: 'privacy@yalantis.com', href: 'mailto:privacy@yalantis.com' }, '.'] },
  ],
}   