// Дані сторінки «Університет» (/university) — записи заходів
// Згенеровано з джерела; title = accent (помаранч.) + rest (ink), рендер uppercase.

export const UNIVERSITY = {
  breadcrumbs: [
    { label: 'Головна', href: '/' },
    { label: 'Університет' },
  ],
  title: 'Заходи для початківців',
  tabs: {
    records: 'Записи заходів',
    schedule: 'Розклад заходів',
  },
  emptySchedule: {
    title: 'Наразі у нас не заплановано подій',
    text: 'Ви можете переглянути записи минулих заходів',
    cta: 'Перейти до записів',
  },
}

export const UNIVERSITY_EVENTS = [
  {
    href: 'https://yalantis.ua/education/yak-obraty-svoyu-sferu-v-it/',
    image: 'https://yalantis.ua/wp-content/uploads/2024/01/yalantis-education_fb-1-1.webp',
    accent: 'Як обрати свою сферу в IT?',
    rest: '',
    text: 'Отримати запис події',
    tags: ['Junior', 'Trainee', 'Work'],
  },
  {
    href: 'https://yalantis.ua/education/yak-uspishno-projty-spivbesidu-v-it-kompaniyu/',
    image: 'https://yalantis.ua/wp-content/uploads/2024/01/yalantis-education_fb-_2_.webp',
    accent: 'Як успішно пройти співбесіду',
    rest: 'в IT-компанію?',
    text: 'Отримати запис події',
    tags: ['Trainee'],
  },
  {
    href: 'https://yalantis.ua/education/yak-apgrejdnuty-cv-shhob-otrymaty-ofer-u-2022-roczi/',
    image: 'https://yalantis.ua/wp-content/uploads/2024/01/yalantis-education_fb-7.webp',
    accent: 'Як апгрейднути CV,',
    rest: 'щоб отримати офер у 2022 році',
    text: 'Отримати запис події',
    tags: ['Trainee'],
  },
  {
    href: 'https://yalantis.ua/education/shho-govoryty-na-spivbesidi-yakshho-u-tebe-nyzkyj-riven-anglijskoyi/',
    image: 'https://yalantis.ua/wp-content/uploads/2024/01/yalantis-education_fb-6.webp',
    accent: 'Що говорити на співбесіді,',
    rest: 'якщо у тебе низький рівень англійської?',
    text: 'Отримати запис події',
    tags: ['English', 'Junior', 'Trainee', 'Work'],
  },
  {
    href: 'https://yalantis.ua/education/daily-meetings-yaki-vyrazy-ta-konstrukcziyi-vykorystovuvaty-shhob-rozpovisty-pro-svoyu-robotu/',
    image: 'https://yalantis.ua/wp-content/uploads/2024/01/yalantis-education_fb-5.webp',
    accent: 'Daily meetings:',
    rest: 'які вирази та конструкції використовувати, щоб розповісти про свою роботу',
    text: 'Отримати запис події',
    tags: ['Junior', 'Trainee', 'Work'],
  },
  {
    href: 'https://yalantis.ua/education/chomu-kompaniyi-vidmovlyayut-junior-ta-trainee-speczialistam-pid-chas-tehnichnoyi-spivbesidy/',
    image: 'https://yalantis.ua/wp-content/uploads/2024/01/yalantis-education_fb-9.webp',
    accent: 'Чому компанії відмовляють Junior та Trainee спеціалістам',
    rest: 'під час технічної співбесіди',
    text: 'Отримати запис події',
    tags: ['Junior', 'Trainee', 'Work'],
  },
  {
    href: 'https://yalantis.ua/education/yak-rozibratys-junior-ta-trainee-speczialistam-u-tehnichnij-dokumentacziyi-anglijskoyu/',
    image: 'https://yalantis.ua/wp-content/uploads/2024/01/yalantis-education_fb-10.webp',
    accent: 'Як розібратись Junior та Trainee спеціалістам',
    rest: 'у технічній документації англійською?',
    text: 'Отримати запис події',
    tags: ['English', 'Junior', 'Trainee', 'Work'],
  },
  {
    href: 'https://yalantis.ua/education/yaki-soft-skills-dopomozhut-vam-ne-vtraty-robotu-u-pershi-dni-ta-zakripytys-u-kompaniyi/',
    image: 'https://yalantis.ua/wp-content/uploads/2024/01/yalantis-education_fb-4.webp',
    accent: 'Які soft skills допоможуть вам',
    rest: 'не втрати роботу у перші дні та закріпитись у компанії?',
    text: 'Отримати запис події',
    tags: ['Junior', 'Trainee', 'Work'],
  },
  {
    href: 'https://yalantis.ua/education/shho-potribno-shhob-staty-back-end-rozrobnykom-i-yak-zhyty-z-czym-dali/',
    image: 'https://yalantis.ua/wp-content/uploads/2024/01/yalantis-education_fb-8.webp',
    accent: 'Що потрібно щоб стати',
    rest: 'Back-end розробником і як жити з цим далі?',
    text: 'Отримати запис події',
    tags: ['Back-end', 'Junior', 'Trainee'],
  },
  {
    href: 'https://yalantis.ua/education/yak-pidgotuvatys-do-spivbesidy-na-pozycziyu-junior-quality-assurance-specialist/',
    image: 'https://yalantis.ua/wp-content/uploads/2024/01/yalantis-education_fb-1.webp',
    accent: 'Як підготуватись до співбесіди',
    rest: 'на позицію Junior Quality Assurance Specialist',
    text: 'Отримати запис події',
    tags: ['Junior', 'QA', 'Trainee', 'Work'],
  },
  {
    href: 'https://yalantis.ua/education/yak-vyvchaty-anglijsku-studentam-shhob-maty-dostatno-znan-dlya-roboty-v-it/',
    image: 'https://yalantis.ua/wp-content/uploads/2024/01/yalantis-education_fb-2.webp',
    accent: 'Як вивчати англійську студентам,',
    rest: 'щоб мати достатньо знань для роботи в ІТ?',
    text: 'Отримати запис події',
    tags: ['English', 'Junior', 'Trainee', 'Work'],
  },
  {
    href: 'https://yalantis.ua/education/shho-potribno-znaty-i-vmity-pochatkivczyu-ios-rozrobnyku-shhob-znajty-robotu/',
    image: 'https://yalantis.ua/wp-content/uploads/2024/01/yalantis-education_fb-3.webp',
    accent: 'Що потрібно знати і вміти початківцю iOS-розробнику,',
    rest: 'щоб знайти роботу?',
    text: 'Отримати запис події',
    tags: ['iOS', 'Junior', 'Trainee'],
  },
  {
    href: 'https://yalantis.ua/education/shho-potribno-front-end-rozrobnyku-pochatkivczyu-shhob-znajty-robotu-u-2022-roczi/',
    image: 'https://yalantis.ua/wp-content/uploads/2023/12/yalantis-education_fb.png',
    accent: 'Що потрібно Front-end розробнику-початківцю,',
    rest: 'щоб знайти роботу у 2022 році?',
    text: 'Отримати запис події',
    tags: ['Front-end', 'Junior', 'Trainee'],
  },
  {
    href: 'https://yalantis.ua/education/english-pershiy-ofer/',
    image: 'https://yalantis.ua/wp-content/uploads/2023/12/yalantis-education_fb-8.webp',
    accent: 'Що справді потрібно при вивченні англійської,',
    rest: 'щоб отримати перший офер?',
    text: 'Отримати запис події',
    tags: ['English', 'Junior', 'Trainee', 'Work'],
  },
  {
    href: 'https://yalantis.ua/education/android-meetup-juniors/',
    image: 'https://yalantis.ua/wp-content/uploads/2023/12/yalantis-education_fb-4.webp',
    accent: 'Що потрібно знати і вміти початківцю Android-розробнику,',
    rest: 'щоб знайти роботу?',
    text: 'Отримати запис події',
    tags: ['Android', 'Junior', 'Trainee'],
  },
  {
    href: 'https://yalantis.ua/education/net-vid-desktop-do-ai/',
    image: 'https://yalantis.ua/wp-content/uploads/2023/12/yalantis-education_fb-7.webp',
    accent: 'Невичерпні можливості .NET:',
    rest: 'від Desktop до AI',
    text: 'Отримати запис події',
    tags: ['.NET', 'Junior', 'Trainee'],
  },
  {
    href: 'https://yalantis.ua/education/komunikacziya-z-rekruterom-pid-chas-vidklyuchen-ta-vijny-yak-zbilshyty-shans-otrymaty-ofer/',
    image: 'https://yalantis.ua/wp-content/uploads/2023/12/yalantis-education_fb-1.webp',
    accent: 'Комунікація з рекрутером під час відключень та війни:',
    rest: 'як збільшити шанс отримати офер',
    text: 'Отримати запис події',
    tags: ['Junior', 'Trainee', 'Work'],
  },
  {
    href: 'https://yalantis.ua/education/devops-meetup-for-juniors/',
    image: 'https://yalantis.ua/wp-content/uploads/2023/12/yalantis-education_fb-2.webp',
    accent: 'Від новачка до ніндзя :',
    rest: 'План успіху спеціаліста DevOps',
    text: 'Отримати запис події',
    tags: ['DevOps', 'Junior', 'Trainee'],
  },
  {
    href: 'https://yalantis.ua/education/strategiya-poshuku-pershoyi-roboty/',
    image: 'https://yalantis.ua/wp-content/uploads/2023/11/2023-12-04-13.39.40.webp',
    accent: 'Стратегія пошуку першої роботи',
    rest: '',
    text: '',
    tags: ['Junior', 'Trainee', 'Work'],
  },
  {
    href: 'https://yalantis.ua/education/perspektyvy-u-python/',
    image: 'https://yalantis.ua/wp-content/uploads/2023/11/yalantis-education_fb-5.webp',
    accent: 'Які перспективи у Python розробників у 2023 році та',
    rest: 'що вам допоможе не втратити першу роботу!',
    text: 'Отримати запис події',
    tags: ['Junior', 'Phyton', 'Trainee'],
  },
  {
    href: 'https://yalantis.ua/education/qa-meetup-for-juniors/',
    image: 'https://yalantis.ua/wp-content/uploads/2023/11/yalantis-education_fb-9.webp',
    accent: 'Що потрібно знати та вміти',
    rest: 'Junior Test Automation Engineer?',
    text: 'Отримати запис події',
    tags: ['Junior', 'Test Automation Engineer', 'Trainee'],
  },
  {
    href: 'https://yalantis.ua/education/golang-for-juniors/',
    image: 'https://yalantis.ua/wp-content/uploads/2023/11/yalantis-education_fb-3.webp',
    accent: 'Які знання та навички необхідні початківцю у Golang,',
    rest: 'щоб отримати офер?',
    text: 'Отримати запис події',
    tags: ['Golang', 'Junior', 'Trainee'],
  },
  {
    href: 'https://yalantis.ua/education/rust-event-for-junior/',
    image: 'https://yalantis.ua/wp-content/uploads/2023/11/yalantis-education_fb.webp',
    accent: 'Довгий шлях до',
    rest: 'першого комерційного досвіду або до чого тут Rust?',
    text: 'Отримати запис події',
    tags: ['Junior', 'Rust', 'Trainee'],
  },
]